name: Prod Tests
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      #- name: Run Linting
      # run: npm run lint
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start Test Execution Timer
        id: start_time
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV
      - name: Run Playwright Cucumber tests
        run: |
          npm run prod:regression
          if grep -q '"status": "failed"' test-result/cucumber-report/cucumber-report.json; then
            echo "Cucumber scenarios failed."
            exit 1
          fi
      - name: Calculate Total Test Duration
        if: ${{ always() }}
        id: end_time
        run: |
            end_time=$(date +%s)
            duration=$((end_time - $start_time))
            echo "total_duration=${duration}" >> $GITHUB_ENV
            echo "Total Test Duration: $((duration / 60))m $((duration % 60))s"
      - name: Upload Playwright Cucumber Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Cucumber Reports
          path: test-result/cucumber-report
          retention-days: 30
      - name: Generate CTRF Report
        if: ${{ always() }}
        run: |
            npm run generate:ctrf
      - name: Add CTRF Report to GitHub Actions Summary
        if: ${{ always() }}
        run: |
            echo "- ## Total Duration : $((total_duration / 60))m $((total_duration % 60))s" >> $GITHUB_STEP_SUMMARY
            cat ./ctrf-report.md >> $GITHUB_STEP_SUMMARY